### ISSUE TITLE
Unable to build the app on azure DevOps: CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'PurchasesHybridCommon' from project 'Pods')

### ISSUE THREAD

**Issue by maciejtutak** [RevenueCat/react-native-purchases#347]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues) #200  #340 #246 #194

**Describe the bug**
Hello,
We are experiencing issues when trying to integrate `react-native-purchases` into our RN app. It's only happening when building our IPA on the azure DevOps pipelines using a fairly standard configuration. It's working when building/archiving locally on dev machines.

The error:

```
The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'PurchasesHybridCommon' from project 'Pods')
	CompileSwift normal arm64 /Users/runner/work/1/s/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/PurchasesHybridCommon.swift (in target 'PurchasesHybridCommon' from project 'Pods')
(2 failures)
##[error]Error: The process '/usr/bin/xcodebuild' failed with exit code 65
```

Here are the relevant bits:

```
  - task: 'CocoaPods@0'
    displayName: pod install
    inputs:
      workingDirectory: ios
```

```
  - task: Xcode@5
    displayName: Build the ${{parameters.country}} IPA
    inputs:
      actions: 'clean build'
      configuration: ${{parameters.country}}.Release
      xcWorkspacePath: ios/app.xcworkspace
      scheme: ${{parameters.country}}
      packageApp: true
      exportPath: output/iphoneos/${{ parameters.buildType }}
      signingOption: manual
     [signing options...]
```

```
+  - Purchases (3.14.1):
+    - PurchasesCoreSwift (= 3.14.1)
+  - PurchasesCoreSwift (3.14.1)
+  - PurchasesHybridCommon (2.0.1):
+    - Purchases (= 3.14.1)

+  - RNPurchases (4.5.3):
+    - PurchasesHybridCommon (= 2.0.1)
```

We are not using Hermes in CI/Flipper, we are not linking any pods manually.

1. Environment
   1. Platform: macOS/azure DevOps [azure pipelines docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=azure-devops) it's using macOS 11 Big Sur internally
   2. SDK version: 4+, `react-native-purchases 4.5.3`
   3. OS version: iphoneos15.2
   4. Xcode/Android Studio version: 13.3
   5. React Native version: 0.67.3
   6. SDK installation (CocoaPods + version or manual): CocoaPods 1.11.3
   7. How widespread is the issue. Percentage of devices affected. N/A
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
I was able to replicate this error once on my local machine and reinstalling pods fixed this problem and it hasn't happened ever since. We tried multiple suggested solutions, but to no success.
